### ISSUE TITLE
AWS Elasticache Restrictions

### ISSUE THREAD

**Issue by brianqcgames** [Grokzen/redis-py-cluster#189]
The config command is restricted when using a Redis cluster in Elasticache making connections fail.

Traceback (most recent call last):
  File "C:/Python27/redistest.py", line 4, in <module>
    rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
  File "C:\Python27\lib\site-packages\rediscluster\client.py", line 181, in __init__
    **kwargs
  File "C:\Python27\lib\site-packages\rediscluster\connection.py", line 141, in __init__
    self.nodes.initialize()
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 228, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 270, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 270, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 267, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "C:\Python27\lib\site-packages\redis\client.py", line 620, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "C:\Python27\lib\site-packages\redis\client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "C:\Python27\lib\site-packages\redis\client.py", line 585, in parse_response
    response = connection.read_response()
  File "C:\Python27\lib\site-packages\redis\connection.py", line 582, in read_response
    raise response
ResponseError: unknown command 'CONFIG'

**Comment by svrana** [comment]
Create your StrictRedisCluster with the option: skip_full_coverage_check=False

**Comment by Grokzen** [comment]
@brianqcgames Are you trying the latest release?

Also this issue has been up before if you do a quick search in the issues list.

The solution is the following when creating your client instance.

```
        :skip_full_coverage_check:
            Skips the check of cluster-require-full-coverage config, useful for clusters
            without the CONFIG command (like aws)
```

**Comment by brianqcgames** [comment]
Thanks

**Comment by AngusP** [comment]
```
ResponseError: unknown command 'CONFIG'
```

This is almost always because the command has been renamed via a config file directive, **for example**: 
```
rename-command CONFIG "CONFIG_U7RkgZ693DG3Fasn"
```
What, specifically, the command has been renamed to will depend on the redis config file the server is using; I haven't used *AWS Elasticache* so I'm afraid I don't know where it'll be shown. If something is renamed to `""` (empty string) the command is basically deleted.

 `redis-py` doesn't seem to have support for command renaming, at least not explicitly. It might make sense to raise an issue there if this is the root cause of your exception as `redis-py-cluster` is built on-top of `redis-py`. Renaming commands has been raised before in August 2016 (https://github.com/andymccurdy/redis-py/pull/776) but was closed without adding functionality.

For what it's worth, the lower level function `execute_command` can be used like so:
```python
r.execute_command('CONFIG_U7RkgZ693DG3Fasn GET', '*')
```
And will return a raw response as `redis-py` won't know which callback to use as it doesn't know the renamed `CONFIG_U7RkgZ693DG3Fasn` command. The callbacks are all in `redis.RESPONSE_CALLBACKS` so you could add one for the renamed command:

```python
>>> r = redis.StrictRedis(...)
...
>>> r.RESPONSE_CALLBACKS['CONFIG_U7RkgZ693DG3Fasn SET'] = r.RESPONSE_CALLBACKS['CONFIG SET']
# You'd have to do this for each of CONFIG SET, GET, REWRITE and RESETSTAT
# Example of a callback:
>>> r.RESPONSE_CALLBACKS['CONFIG GET']
<function redis.client.parse_config_get>
```

I would agree it'd be useful for `redis-py` to have a function to do this. Most (sane) cluster production setups will have renamed the `CONFIG`, `FLUSHALL`, `FLUSHDB`, `DEBUG` and `SHUTDOWN` commands.

**Comment by mingtm** [comment]
The same issue still happens:

from rediscluster import StrictRedisCluster
startup_nodes = [{"host": "xxxx.clustercfg.apn2.cache.amazonaws.com", "port": "6379"}]
r = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=False)
r.set('foo', 'bar')
value = r.get('foo')

======
Exception:
Traceback (most recent call last):
  File "testRedisCluster.py", line 11, in <module>
    r = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=False)
  File "/Library/Python/2.7/site-packages/rediscluster/client.py", line 181, in __init__
    **kwargs
  File "/Library/Python/2.7/site-packages/rediscluster/connection.py", line 141, in __init__
    self.nodes.initialize()
  File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 228, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 270, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 270, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 267, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "/Library/Python/2.7/site-packages/redis/client.py", line 715, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Library/Python/2.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'CONFIG'

I'm using redis-py-cluster 1.3.4.

Any idea?

**Comment by EvanLeeC** [comment]
@mingtm skip_full_coverage_check=True
