### ISSUE TITLE
Intermittent but fairly frequent "Connection refused" error

### ISSUE THREAD

**Issue by kunal-bajpai** [Grokzen/redis-py-cluster#190]
```
[kajaybaj@kajaybaj-ld1 bin]$ ./redis-server --port 5000 --cluster-enabled yes
(redis) [kajaybaj@kajaybaj-ld1 redis]$ python
Python 3.4.3 (default, Mar 28 2017, 17:16:04)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rediscluster import StrictRedisCluster
>>> s=StrictRedisCluster(host="localhost",port=5000)
Traceback (most recent call last):
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 439, in connect
    sock = self._connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 494, in _connect
    raise err
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/client.py", 
line 572, in execute_command
    connection.send_command(*args)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 538, in send_packed_command
    self.connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:0. Connectio
n refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 439, in connect
    sock = self._connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 494, in _connect
    raise err
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/clien
t.py", line 181, in __init__
    **kwargs
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/conne
ction.py", line 141, in __init__
    self.nodes.initialize()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodem
anager.py", line 228, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodem
anager.py", line 270, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodem
anager.py", line 270, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodem
anager.py", line 267, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/client.py", 
line 620, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/client.py", 
line 578, in execute_command
    connection.send_command(*args)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 538, in send_packed_command
    self.connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.p
y", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:0. Connectio
n refused.
```

**Comment by Grokzen** [comment]
@kunal-bajpai Problems with the underlying redis module is not something i deal with here. Unless you can prove that this module is responsible for something that cause it to connect to wrong place then i can investigate it but form what i see there is no evidence of that from the stacktrace you post.

Why do it try to connect to port 0??

**Comment by kunal-bajpai** [comment]
@Grokzen I cannot figure out where on earth that port 0 is coming from. I was hoping you would have seen this before. I'll try and dig more but I have dug quite a bit already.
Also, is there any reason for handling exceptions like this:
```
179             except ConnectionError:
180                 continue
181             except Exception:
182                 raise RedisClusterException("ERROR sending 'cluster slots' command to redis server: {0}".format(node))
```
This leads to rather complicated stack traces don't you think?

**Comment by kunal-bajpai** [comment]
I think I found something
I added a print in rediscluster/nodemanager.py
```
198
199                 node, node_name = self.make_node_obj(master_node[0], master_node[1], 'master')
200                 nodes_cache[node_name] = node
201                 print(nodes_cache)
202                 for i in range(int(slot[0]), int(slot[1]) + 1):
203                     if i not in tmp_slots:
```
It leads to this
```
(redis) [kajaybaj@kajaybaj-ld1 redis]$ python
Python 3.4.3 (default, Mar 28 2017, 17:16:04)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rediscluster import StrictRedisCluster
>>> s=StrictRedisCluster(host="localhost",port=5000)
{'localhost:0': {'port': 0, 'name': 'localhost:0', 'host': 'localhost', 'server_type': 'master'}}
{'localhost:0': {'port': 0, 'name': 'localhost:0', 'host': 'localhost', 'server_type': 'master'}, '127.0.0.1:5000': {'port': 5000, 'name': '127.0.0.1:5000', 'host': '127.0.0.1', 'server_type': 'master'}}
{'localhost:0': {'port': 0, 'name': 'localhost:0', 'host': 'localhost', 'server_type': 'master'}, '127.0.0.1:5000': {'port': 5000, 'name': '127.0.0.1:5000', 'host': '127.0.0.1', 'server_type': 'master'}}
Traceback (most recent call last):
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:0. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/client.py", line 181, in __init__
    **kwargs
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/connection.py", line 141, in __init__
    self.nodes.initialize()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodemanager.py", line 227, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodemanager.py", line 269, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodemanager.py", line 269, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/rediscluster/nodemanager.py", line 266, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/client.py", line 620, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/kajaybaj/code/redis/lib/python3.4/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:0. Connection refused.
```
Notice the lines printed before the error
```
{'localhost:0': {'port': 0, 'name': 'localhost:0', 'host': 'localhost', 'server_type': 'master'}}
{'localhost:0': {'port': 0, 'name': 'localhost:0', 'host': 'localhost', 'server_type': 'master'}, '127.0.0.1:5000': {'port': 5000, 'name': '127.0.0.1:5000', 'host': '127.0.0.1', 'server_type': 'master'}}
{'localhost:0': {'port': 0, 'name': 'localhost:0', 'host': 'localhost', 'server_type': 'master'}, '127.0.0.1:5000': {'port': 5000, 'name': '127.0.0.1:5000', 'host': '127.0.0.1', 'server_type': 'master'}}
```
This happens in NodeManager.initialize() which, according to the stacktrace is before any calls to underlying redis. Looks like it is coming from this module @Grokzen 
Does this help?

**Comment by kunal-bajpai** [comment]
[[1, 3, ['', 0, 'f538c5e6df2b6d5431e9ff8e049125d8e100f0d3']], 
[15495, 15495, ['127.0.0.1', 5000, '8be7ecb0e656df23392ef5a865028eb8a5c554f1']]]
^ result of CLUSTER SLOTS. Slots 0-3 are assigned to '':0. Hostname is fixed from '' to 'localhost here but port remains 0
```
186             # If there's only one server in the cluster, its ``host`` is ''
187             # Fix it to the host in startup_nodes
188             if (len(cluster_slots) == 1 and len(cluster_slots[0][2][0]) == 0 and len(self.startup_nodes) == 1):
189                 cluster_slots[0][2][0] = self.startup_nodes[0]['host']
```

**Comment by kunal-bajpai** [comment]
Was caused by a bad nodes.conf in the folder while initialising redis-server.

Thanks!

**Comment by Grokzen** [comment]
@kunal-bajpai thanks for reporting back and closing the issue :)
