### ISSUE TITLE
ImportError: cannot import name StrictRedisCluster

### ISSUE THREAD

**Issue by foodini** [Grokzen/redis-py-cluster#192]
Following the README.md process, I've installed redis-py-cluster, and it works in ipython, but not in the python binary. I've had a coworker - also on an OS X 10.11.1 box - attempt exactly the same thing and he gets no issue. Note that I have upgraded pip to version 9.01 and still have a problem.

```
> python --version
Python 2.7.13

> ipython --version
5.3.0

> mkvirtualenv --version
12.0.6

> mkvirtualenv redis
New python executable in redis/bin/python2.7
Also creating executable in redis/bin/python
Installing setuptools, pip...done.
virtualenvwrapper.user_scripts creating .../.virtualenvs/redis/bin/predeactivate
virtualenvwrapper.user_scripts creating .../.virtualenvs/redis/bin/postdeactivate
virtualenvwrapper.user_scripts creating .../.virtualenvs/redis/bin/preactivate
virtualenvwrapper.user_scripts creating .../.virtualenvs/redis/bin/postactivate
virtualenvwrapper.user_scripts creating .../.virtualenvs/redis/bin/get_env_details

> pip install redis-py-cluster
You are using pip version 6.0.7, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting redis-py-cluster
  Using cached redis_py_cluster-1.3.4-py2.py3-none-any.whl
Collecting redis>=2.10.2 (from redis-py-cluster)
  Using cached redis-2.10.5-py2.py3-none-any.whl
Installing collected packages: redis, redis-py-cluster

Successfully installed redis-2.10.5 redis-py-cluster-1.3.4


> python    #note that "python foo.py" produces the same issue.
Python 2.7.9 (default, Jan 29 2015, 06:27:40)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rediscluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.virtualenvs/redis/lib/python2.7/site-packages/rediscluster/__init__.py", line 7, in <module>
    from .client import StrictRedisCluster, RedisCluster
  File ".../.virtualenvs/redis/lib/python2.7/site-packages/rediscluster/client.py", line 10, in <module>
    from .connection import ClusterConnectionPool, ClusterReadOnlyConnectionPool
  File ".../.virtualenvs/redis/lib/python2.7/site-packages/rediscluster/connection.py", line 11, in <module>
    from .nodemanager import NodeManager
  File ".../.virtualenvs/redis/lib/python2.7/site-packages/rediscluster/nodemanager.py", line 8, in <module>
    from .exceptions import RedisClusterException
  File ".../.virtualenvs/redis/lib/python2.7/site-packages/rediscluster/exceptions.py", line 3, in <module>
    from redis.exceptions import (
  File "redis.py", line 5, in <module>
    from rediscluster import StrictRedisCluster
ImportError: cannot import name StrictRedisCluster
>>>^D

```

The file, redis.py, exists nowhere in my virtual environment. The string, "from rediscluster import StrictRedisCluster" exists in none of the python files in my virtual environment.

```
> ipython
imp/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py:724: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
orPython 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from rediscluster import StrictRedisCluster

In [2]: rc = StrictRedisCluster(host='127.0.0.1', port=7000)

In [3]: rc.set('foo', 'bar')
Out[3]: True

In [4]: rc.get('foo')
Out[4]: 'bar'
```

**Comment by foodini** [comment]
The redis.py it was finding turned out to be an orphaned redis.pyc in ~. My home directory is not in my python path. Feel free to delete the issue.
