### ISSUE TITLE
rename command error

### ISSUE THREAD

**Issue by Icepo** [Grokzen/redis-py-cluster#203]
While I test the rename command, it says 【UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 2: invalid continuation byte】。So I had checked all the documents make sure they have [# -*- coding: UTF-8 -*-]。
Other command such as get，set,  zadd, zcard, delete all work。

**Comment by Grokzen** [comment]
Try adding `decode_responses` variable to your StrictRedisCluster object as example here shows https://github.com/Grokzen/redis-py-cluster/blob/unstable/README.md#usage-example

```
>>> from rediscluster import StrictRedisCluster

>>> # Requires at least one node for cluster discovery. Multiple nodes is recommended.
>>> startup_nodes = [{"host": "127.0.0.1", "port": "7000"}]

>>> rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)

>>> rc.set("foo", "bar")
True
>>> print(rc.get("foo"))
'bar'
```

**Comment by dikang123** [comment]
actually,I found the same error, even I add decode_responses variable to StrictRedisCluster object!
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python27/lib/python2.7/site-packages/rediscluster/client.py", line 783, in renamenx
    return self.rename(src, dst)
  File "/usr/local/python27/lib/python2.7/site-packages/rediscluster/client.py", line 740, in rename
    data = self.dump(src)
  File "/usr/local/python27/lib/python2.7/site-packages/redis/client.py", line 947, in dump
    return self.execute_command('DUMP', name)
  File "/usr/local/python27/lib/python2.7/site-packages/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/usr/local/python27/lib/python2.7/site-packages/rediscluster/client.py", line 371, in execute_command
    return self.parse_response(r, command, **kwargs)
  File "/usr/local/python27/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/python27/lib/python2.7/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/local/python27/lib/python2.7/site-packages/redis/connection.py", line 326, in read_response
    response = self.encoder.decode(response)
  File "/usr/local/python27/lib/python2.7/site-packages/redis/connection.py", line 125, in decode
    value = value.decode(self.encoding, self.encoding_errors)
  File "/usr/local/python27/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 8: invalid start byte
'''

**Comment by dikang123** [comment]
a-ha, when I set 'decode_responses' to False, the ERROR does not exist! interesting~~

**Comment by mfisher35** [comment]
I'm getting this error to.  I'd prefer not to have to set decode_responses to False
