### ISSUE TITLE
ImportError: No module named 'redis.exceptions'; 'redis' is not a package

### ISSUE THREAD

**Issue by tmshn** [Grokzen/redis-py-cluster#207]
Hi, I've just tried to use this library, but bumped into the problem at the very beginning: `import rediscluster` gives me an `ImportError`

```python
>>> import rediscluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/var/pyenv/versions/3.5.3/lib/python3.5/site-packages/rediscluster/__init__.py", line 7, in <module>
    from .client import StrictRedisCluster, RedisCluster
  File "/usr/local/var/pyenv/versions/3.5.3/lib/python3.5/site-packages/rediscluster/client.py", line 10, in <module>
    from .connection import ClusterConnectionPool, ClusterReadOnlyConnectionPool
  File "/usr/local/var/pyenv/versions/3.5.3/lib/python3.5/site-packages/rediscluster/connection.py", line 11, in <module>
    from .nodemanager import NodeManager
  File "/usr/local/var/pyenv/versions/3.5.3/lib/python3.5/site-packages/rediscluster/nodemanager.py", line 9, in <module>
    from .exceptions import RedisClusterException
  File "/usr/local/var/pyenv/versions/3.5.3/lib/python3.5/site-packages/rediscluster/exceptions.py", line 3, in <module>
    from redis.exceptions import (
ImportError: No module named 'redis.exceptions'; 'redis' is not a package
```

The step to reproduce is as simple as follows:
1. Prepare clean Python: I did `pyenv install 3.5.3 && pyenv local 3.5.3`
1. Install redis-py-cluster: `pip install redis-py-cluster`
1. Just import: `import rediscluster`

For more info:
```bash
$ pip freeze
redis==2.10.5
redis-py-cluster==1.3.4
```

I'm currently using macOS, but I encountered same error on Ubuntu 16.04 and Google App Engine flexible environment.

Can anyone have idea about this?

**Comment by tmshn** [comment]
Sorry. Submitted issue, and relaxed, then I noticed the problem.
The reason for the error is that I have a python script named `redis.py` in the working directory and `import redis` tries to import this file rather than pip-installed `redis` package.
Totally my mistake :bow:, so close the issue.

**Comment by Grokzen** [comment]
@tmshn This is a common misstake and the solution is allways that you have a file in your import path before your external modules :)
