### ISSUE TITLE
raise ConnectionError when one of cluster master node down

### ISSUE THREAD

**Issue by wenxuanguan** [Grokzen/redis-py-cluster#211]
I run a four-node redis-cluster with config `cluster-require-full-coverage=no`, where one master node(127.0.0.1:7381) down,  data visit in other connected node should be normal. 
However, when i  init StrictRedisCluster, `ConnectionError ` raised.
```python
Traceback (most recent call last):
  File "E:/pyworkplace/reliability/script/t.py", line 54, in <module>
    client = RedisClient('127.0.0.1:6380')
  File "E:/pyworkplace/reliability/script/t.py", line 18, in __init__
    self.client = StrictRedisCluster(skip_full_coverage_check=True, host='127.0.0.1', port=6380)
  File "C:\Python27\lib\site-packages\rediscluster\client.py", line 157, in __init__
    **kwargs
  File "C:\Python27\lib\site-packages\rediscluster\connection.py", line 83, in __init__
    self.nodes.initialize()
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 190, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 225, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 225, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "C:\Python27\lib\site-packages\rediscluster\nodemanager.py", line 222, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "build\bdist.win32\egg\redis\client.py", line 620, in config_get
  File "build\bdist.win32\egg\redis\client.py", line 578, in execute_command
  File "build\bdist.win32\egg\redis\connection.py", line 563, in send_command
  File "build\bdist.win32\egg\redis\connection.py", line 538, in send_packed_command
  File "build\bdist.win32\egg\redis\connection.py", line 442, in connect
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:7381. .
```
What i know from stack trace is StrictRedisCluster send command to get config `cluster-require-full-coverage` when init, While failed master node is disconnected.

Also, I found no way to skip the step, get config `cluster-require-full-coverage` .

- env
redis-cluster: 3.0.3
redis-py-cluster: 1.2.0

**Comment by Grokzen** [comment]
@wenxuanguan Have you tested to rerun this case/scneario with a later version of redis-py-cluster? 1.2.0 is kinda old and things might have changed since 1.2.0.

I am not totally sure about simply swallow the error would improve things becuase if one of your masters is down in your cluster that you probably have defined, you might want that error to propegate up to your caller of the client class.

I will put this on the backburner some and think about it some if i want to change the overall behaviour of the feature or not.
