### ISSUE TITLE
AWS Redis Cluster fails with CONFIG (already set skip_full_coverage_check=False)

### ISSUE THREAD

**Issue by mingtm** [Grokzen/redis-py-cluster#235]
The same issue still happens:

```
from rediscluster import StrictRedisCluster
startup_nodes = [{"host": "xxxx.clustercfg.apn2.cache.amazonaws.com", "port": "6379"}]
r = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=False)
r.set('foo', 'bar')
value = r.get('foo')
```

```
Exception:
Traceback (most recent call last):
File "testRedisCluster.py", line 11, in 
r = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=False)
File "/Library/Python/2.7/site-packages/rediscluster/client.py", line 181, in init
**kwargs
File "/Library/Python/2.7/site-packages/rediscluster/connection.py", line 141, in init
self.nodes.initialize()
File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 228, in initialize
need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 270, in cluster_require_full_coverage
return any(node_require_full_coverage(node) for node in nodes.values())
File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 270, in 
return any(node_require_full_coverage(node) for node in nodes.values())
File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 267, in node_require_full_coverage
return "yes" in r_node.config_get("cluster-require-full-coverage").values()
File "/Library/Python/2.7/site-packages/redis/client.py", line 715, in config_get
return self.execute_command('CONFIG GET', pattern)
File "/Library/Python/2.7/site-packages/redis/client.py", line 668, in execute_command
return self.parse_response(connection, command_name, **options)
File "/Library/Python/2.7/site-packages/redis/client.py", line 680, in parse_response
response = connection.read_response()
File "/Library/Python/2.7/site-packages/redis/connection.py", line 629, in read_response
raise response
redis.exceptions.ResponseError: unknown command 'CONFIG'
```

I'm using redis-py-cluster 1.3.4.

Any idea?

**Comment by thethomp** [comment]
Shouldn't skip_full_coverage_check be set to True rather than False, to bypass the CONFIG call?

**Comment by mingtm** [comment]
Oh, Yes. Set to True works now. Thanks!

**Comment by mingtm** [comment]
above issue was resolved. However, when I add multiple key-values, it fails eventually as the following:

Traceback (most recent call last):
  File "loadData.py", line 39, in <module>
    r.sadd(key, values)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 1600, in sadd
    return self.execute_command('SADD', name, *values)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Library/Python/2.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MOVED 4085 xxx.152:6379

Any idea?

**Comment by Grokzen** [comment]
@mingtm This is the second issue that has this MOVED command popping out from the same method `sadd`. I can't really say why this happens or the root cause becuase this is something that happens after a while of use and not instantly repeatable in a stable fashion.

The only common thing that i have noticed in the reports is that you both are using AWS to run the redis-cluster and this client. As i am not using AWS i can't really help in debugging this but it is most probably not a client realted problem as it is more a redis problem inside AWS. Do you have any update on debugging this issue from your end?

**Comment by Grokzen** [comment]
@mingtm The solution to your problem there is that you are not running through the redis-cluster client class but throught the normal redis-py class and it can't handle the MOVED case properly. I would suggest your have some installation error or some configuration error but if you fix your code it should start to work again properly.
