### ISSUE TITLE
ERROR sending 'cluster slots'

### ISSUE THREAD

**Issue by benben17** [Grokzen/redis-py-cluster#255]
rc = StrictRedisCluster(startup_nodes=redisnodes)
  File "build/bdist.macosx-10.6-intel/egg/rediscluster/client.py", line 183, in __init__
  File "build/bdist.macosx-10.6-intel/egg/rediscluster/connection.py", line 143, in __init__
  File "build/bdist.macosx-10.6-intel/egg/rediscluster/nodemanager.py", line 183, in initialize
rediscluster.exceptions.RedisClusterException: ERROR sending 'cluster slots' command to redis server: {'host': '10.10.65.68', 'port': 8813}

我直接用命令行是没有问题的
127.0.0.1:8813> cluster slots
1) 1) (integer) 8192
   2) (integer) 12287
   3) 1) "10.10.65.42"
      2) (integer) 8812
   4) 1) "10.10.65.68"
      2) (integer) 8812
2) 1) (integer) 0
   2) (integer) 4095
   3) 1) "10.10.65.15"
      2) (integer) 8810
   4) 1) "10.10.65.23"
      2) (integer) 8810
3) 1) (integer) 4096
   2) (integer) 8191
   3) 1) "10.10.65.23"
      2) (integer) 8811
   4) 1) "10.10.65.15"
      2) (integer) 8811
4) 1) (integer) 12288
   2) (integer) 16383
   3) 1) "10.10.65.68"
      2) (integer) 8813
   4) 1) "10.10.65.42"
      2) (integer) 8813

**Comment by Grokzen** [comment]
@benben17 Can you connect to the cluster from the same place you run your client via telnet? Configuration or connection error in your cluster setup is NOT a issue in this repo.

**Comment by keerthy-cf** [comment]
Facing the same issue where as able to connect via rediscli and execute the command.

**Comment by Grokzen** [comment]
@keerthy-cf Simply stating that you have the same problem do not get me anywhere in this matter. For me to be able to provide any help in this i need much more detailed information about your setup, versions, what code you are running, what debugging options you have used already and all of that. Without this i will simply close this issue as invalid/not reproducable as this looks more like a configuration issue on your side more than a bug in this code.

**Comment by keerthy-cf** [comment]
@Grokzen  Please find below the details and let me know any more information is needed.
Redis server version  - 3.2.4
Python version in the client - 2.7

Code snippet is as follows and using the latest redis-py-client
```
   from rediscluster import StrictRedisCluster
    startup_nodes = [{"host": "127.0.0.1",
                      "port": "6379"
                      }]
    r = StrictRedisCluster(
        readonly_mode=True,
        startup_nodes=startup_nodes, decode_responses=True, password="password")
   for key in r.scan_iter("*", count=100):
        print "key " + key
```

Error seen is as follows
```
  File "/Library/Python/2.7/site-packages/rediscluster/nodemanager.py", line 183, in initialize
    raise RedisClusterException("ERROR sending 'cluster slots' command to redis server: {0}".format(node))
rediscluster.exceptions.RedisClusterException: ERROR sending 'cluster slots' command to redis server: {'host': '127.0.0.1', 'port': '6379'}
```

Able to connect to the same and execute cluster slots using redis-cli command line utility.

**Comment by Grokzen** [comment]
Yeah, your issue there is that you are using a password to the cluster. There is a item on the TODO list to fix the initialization process to support all connection options that normal commands support. It is basically the same problem as #252

**Comment by keerthy-cf** [comment]
Cool Thanks. Is there any other way to get this working ?

**Comment by Grokzen** [comment]
You should be able to do a local patch here https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L177 i think to get around this issue for now.

**Comment by cdurepo** [comment]
I am getting this same error but I am not using a password.  I am able to run cluster slots via the cli and it seems to work fine. 

here is what I have: 
startup_nodes =[{"host": "172.18.0.8", "port": 6379}]
rdb = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)

Here is the error that I get: 
  File "/usr/lib/python2.7/site-packages/rediscluster/nodemanager.py", line 183, in initialize
    raise RedisClusterException("ERROR sending 'cluster slots' command to redis server: {0}".format(node))
rediscluster.exceptions.RedisClusterException: ERROR sending 'cluster slots' command to redis server: {'host': '172.18.0.8', 'port': 6379}

INFO: 
[root@devel ~]# python --version
Python 2.7.5

[user@devel python]$ redis-cli -h 172.18.0.5 -p 6379 info   
# Server
redis_version:4.0.5

[user@devel python]$ redis-cli -h 172.18.0.5 -p 6379 cluster slots
1) 1) (integer) 6554
   2) (integer) 9829
   3) 1) "172.18.0.8"
      2) (integer) 6379
      3) "08ec3b95dbd100686486f1caa17253d8afd540e9"
2) 1) (integer) 13107
   2) (integer) 16383
   3) 1) "172.18.0.7"
      2) (integer) 6379
      3) "d8f9725f637927fda222e8ae66384db9d60a6dfc"
3) 1) (integer) 0
   2) (integer) 3276
   3) 1) "172.18.0.5"
      2) (integer) 6379
      3) "62c9e4c1d247f01c635e5afd85285f063b603418"
4) 1) (integer) 9830
   2) (integer) 13106
   3) 1) "172.18.0.6"
      2) (integer) 6379
      3) "de1025277ff3036c5ecf53516ed925ca079fe2af"
5) 1) (integer) 3277
   2) (integer) 6553
   3) 1) "172.18.0.4"
      2) (integer) 6379
      3) "d585762bf930e5c5e25e8fabcb822f54d79cbe05"

**Comment by Grokzen** [comment]
@cdurepo This error report is wrong becuase you are fetching info from 2 different nodes in the cluster. You go to `172.18.0.8` in the python case, and cli case `172.18.0.5`. Try the same node first. Also, try to send the same command to the cluster. It could be that you are using a older client version that might not be 4.0.x compatible, but probably not. Also `decode_responses=True` is mostly used for python3 so there is also a possibility it could be the problem.

In general, if you are using plain redis clusters without any special security conf and you can't connect to them, then there is probably a 99% probability that a error on your end and not in this lib.

**Comment by benben17** [comment]
This issue was  solved by upgrade redis cilent。but i don't know why

**Comment by chris1248** [comment]
I had this problem. 
because I was sending in `"ssl_cert_reqs": "None"` instead it should have been: `"ssl_cert_reqs": None`

**Comment by jaxzon** [comment]
I am experiencing similar error. Running 6 node redis cluster in kubernetes cluster.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 226, in initialize
    cluster_slots = r.execute_command("cluster", "slots")
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 664, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: SELECT is not allowed in cluster mode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 120, in sentry_patched_wsgi_handler
    return SentryWsgiMiddleware(bound_old_app)(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 129, in __call__
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 55, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 125, in __call__
    _sentry_start_response, start_response, transaction
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 350, in sentry_patched_get_response
    return old_get_response(self, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "./myproject/views.py", line 57, in server_error
    return HttpResponseServerError(template.render(context, request))
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "./myproject/context_processors.py", line 31, in dj_const_data_processor
    'CATEGORIES': get_serialized_myproject_categories(),
  File "/app/oscar_forks/catalogue/navigation_categories.py", line 24, in get_serialized_myproject_categories
    result = cache.get(cache_key)
  File "/usr/local/lib/python3.7/site-packages/django_redis/cache.py", line 87, in get
    value = self._get(key, default, version, client)
  File "/usr/local/lib/python3.7/site-packages/django_redis/cache.py", line 27, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_redis/cache.py", line 94, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/usr/local/lib/python3.7/site-packages/django_redis/client/default.py", line 215, in get
    client = self.get_client(write=False)
  File "/usr/local/lib/python3.7/site-packages/django_redis/client/default.py", line 94, in get_client
    self._clients[index] = self.connect(index)
  File "/usr/local/lib/python3.7/site-packages/django_redis/client/default.py", line 107, in connect
    return self.connection_factory.connect(self._server[index])
  File "/usr/local/lib/python3.7/site-packages/django_redis/pool.py", line 66, in connect
    connection = self.get_connection(params)
  File "/usr/local/lib/python3.7/site-packages/django_redis/pool.py", line 77, in get_connection
    pool = self.get_or_create_connection_pool(params)
  File "/usr/local/lib/python3.7/site-packages/django_redis/pool.py", line 98, in get_or_create_connection_pool
    self._pools[key] = self.get_connection_pool(params)
  File "/usr/local/lib/python3.7/site-packages/django_redis/pool.py", line 111, in get_connection_pool
    pool = self.pool_cls.from_url(**cp_params)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1070, in from_url
    return cls(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/rediscluster/connection.py", line 160, in __init__
    self.nodes.initialize()
  File "/usr/local/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 238, in initialize
    raise RedisClusterException("ERROR sending 'cluster slots' command to redis server: {0}".format(node))
rediscluster.exceptions.RedisClusterException: ERROR sending 'cluster slots' command to redis server: {'host': 'redis', 'port': '6379'}

```


In django shell everything seems to work:

```
>>> from rediscluster.nodemanager import NodeManager
>>> nodemanager = NodeManager(startup_nodes=[{'host': 'redis', 'port': '6379'}], decode_responses=True)
>>> r = nodemanager.get_redis_link(host='redis', port='6379')
>>> r.execute_command("cluster", "slots")
[[10923, 16383, [b'10.1.9.168', 6379, b'94a30b56f7eda1df557a7c5e8703a230b5c4f08e'],
[b'10.1.9.155', 6379, b'8d051c4bb693b9317a795f3395d3191c5581092b']],
 [5461, 10922, [b'10.1.9.174', 6379, b'3464fdd3e77475c62249c9cb50283843d8b82b1f'],
 [b'10.1.9.161', 6379, b'ab3d16ec2306b44e53dfa8875ad435b2065fa5c6']],
 [0, 5460, [b'10.1.9.139', 6379, b'75076dee5356feeec4c503f9b6058fdfd992eac3'],
 [b'10.1.9.144', 6379, b'23f188b836447859646fc3b45f93096f7ad7e504']]]
```

Part of my requirements.txt
```
amqp==2.6.0
celery[redis]==4.3.0
celery-singleton==0.2.0
python-redis-lock==3.3.1
kombu==4.5.0
Django==2.2.1
psycopg2-binary==2.8.2
redis==3.5.3
redis-py-cluster==2.1.2
django-redis==4.12.1
```

**Comment by Grokzen** [comment]
Then i have no idea why it tries to send SELECT, if you are running the latest version you can try to enable the logging for this lib and see if you get anything from there. Otherwise you need to look through your django side exception why it tries to send SELECT command. There should be nothing in this code that will attempt to send SELECT as that is not supported. You can also see this due to the only line that we are running from thsi lib is `cluster_slots = r.execute_command("cluster", "slots")` so might there be something funky by redis-py doing something fishy?

**Comment by jaxzon** [comment]
Issue was in my django configuration:
```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/2",    -< ISSUE HERE
        "OPTIONS": {
            # "CLIENT_CLASS": "django_redis.client.DefaultClient",
            'REDIS_CLIENT_CLASS': 'rediscluster.RedisCluster',
            'CONNECTION_POOL_CLASS': 'rediscluster.connection.ClusterConnectionPool',
            'CONNECTION_POOL_KWARGS': {
                'skip_full_coverage_check': True
            },
            'ssl_cert_reqs': None
        }
    }
}
```

I had to remove database number from the LOCATION.
I didn't know that redis cluster does not support different databases. Thank you Grokzen!

**Comment by Grokzen** [comment]
@jaxzon That is acctually a kind of a bug and i created #456 to track that issue as it is a bit different code path when you run the parse_url method over the more normal used version of `RedisCluster(..., db=2)`

**Comment by findstockgod** [comment]
I got the same problem.
```
ERROR sending 'cluster slots' command to redis server ...
```

BEFORE :
python 2.7
redis-py-cluster==1.3.5

usage:
conn = StrictRedisCluster(startup_nodes=redis_nodes, password=redis_password)


AFTER:
python 2.7
redis-py-cluster==2.0.0

usage
conn = RedisCluster(startup_nodes=redis_nodes, password=redis_password)

and id worked well.

-----
key change:
1. upgrade redis-py-cluster to 2.0.0
2. change connect : conn = RedisCluster(xxx

**Comment by Grokzen** [comment]
@findstockgod I would recommend that you switch up to python3.x as well. 2.7 is not supported any longer really. Also password protected servers was not well supported in the 1.3.x line
