### ISSUE TITLE
Unexpected keyword argument 'ssl'

### ISSUE THREAD

**Issue by arthur78** [Grokzen/redis-py-cluster#260]
On AWS:
```
# python 3.6
# redis-py-cluster 1.3.4

rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True,
                            skip_full_coverage_check=True, ssl=True)
rc.set('foo', 'bar)
```
  
```
...
  File "/var/task/rediscluster/connection.py", line 44, in __init__
    super(ClusterConnection, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
```

**Comment by Grokzen** [comment]
It looks like the SSL connection_class fix that exists in redis-py is not present in this lib. Should be a easy addition to get in. In the meantime, i think the way to solve it for you is to add `connection_class=SSLClusterConnection` to your `StrictRedisCluster` constructor and also to add along the required additional ssl variables to simulate how it is done here https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L540

**Comment by arthur78** [comment]
Thanks. I've created a PR, but not sure I've done it properly. Please see https://github.com/arthur78/redis-py-cluster/commit/0cdc887c7a9f68567b7a467e5ee139ffe47d334f

**Comment by Grokzen** [comment]
You did well, saw it was your first time contribution on github. The one thing you did not do correct was to base your commit on-top of the `unstable` branch and not on the `master` branch and merge it into `unstable`. This is why you see so many commits that it want to merge inside your PR. When done correct, you should only see your own commit.

**Comment by arthur78** [comment]
Thanks!

**Comment by Grokzen** [comment]
@nishantgeorge This is already in the latest release. Check the commit history and the diff between 1.3.4 and 1.3.5 release

**Comment by nishantgeorge** [comment]
@Grokzen I'm still seeing this with 2.0.0. Am I doing something wrong?
```python
>>> import rediscluster
>>> rediscluster.__version__
'2.0.0'
>>> import redis
>>> redis.__version__
'3.0.1'
>>> rc = rediscluster.RedisCluster(host='redis-cluster', ssl=False)
>>> rc.ping()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rediscluster/connection.py", line 323, in get_connection_by_node
    connection = self._available_connections.get(node["name"], []).pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 980, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.6/site-packages/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rediscluster/client.py", line 369, in execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rediscluster/client.py", line 451, in _execute_command_on_nodes
    connection = self.connection_pool.get_connection_by_node(node)
  File "/usr/local/lib/python3.6/site-packages/rediscluster/connection.py", line 325, in get_connection_by_node
    connection = self.make_connection(node)
  File "/usr/local/lib/python3.6/site-packages/rediscluster/connection.py", line 232, in make_connection
    connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)
  File "/usr/local/lib/python3.6/site-packages/rediscluster/connection.py", line 47, in __init__
    super(ClusterConnection, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
```

**Comment by Grokzen** [comment]
@nishantgeorge You are missing the `startup_nodes=[...]` argument into the `RedisCluster` class. The problem is not the `ssl` argument
