### ISSUE TITLE
Not able to send commands through pipeline

### ISSUE THREAD

**Issue by Chatheersh** [Grokzen/redis-py-cluster#266]
I have the following script to connect to my redis cluster:

```from rediscluster import StrictRedisCluster
from datetime import datetime

start_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

startup_nodes = [{"host": "redis01-staging-tor", "port": "7000"}]
redis_client = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
p = redis_client.pipeline()

p.command_stack = []

for i in range(1, 1000):
    p.command_stack.append((["SET", "foo{}".format(i), "bar{}".format(i)], {}))

p.execute()

end_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

print("start_time: {}".format(start_time))
print("end_time:   {}".format(end_time))
```

When I attempt to run the script I get the following error:

```
Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    p.execute()
  File "/Users/chat/anaconda3/lib/python3.6/site-packages/rediscluster/pipeline.py", line 98, in execute
    return self.send_cluster_commands(stack, raise_on_error)
  File "/Users/chat/anaconda3/lib/python3.6/site-packages/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/Users/chat/anaconda3/lib/python3.6/site-packages/rediscluster/pipeline.py", line 144, in send_cluster_commands
    attempt = sorted(stack, key=lambda x: x.position)
  File "/Users/chat/anaconda3/lib/python3.6/site-packages/rediscluster/pipeline.py", line 144, in <lambda>
    attempt = sorted(stack, key=lambda x: x.position)
AttributeError: 'tuple' object has no attribute 'position'
```

Is there a bug in the code?  I followed the example from the following:
http://redis-py-cluster.readthedocs.io/en/master/pipelines.html#multi-exec-cluster-test-code

**Comment by Grokzen** [comment]
The main issue with your example is that it is not a Example code piece on how to use and code pipelines. Appending directly to the command_stack variable is a very low level solution that should not be used unless there is some unsupported feature/command in the lib that you require, then you should use the command stack. The correct way is to create a pipeline object and use the normal SET/GET methods like you would the normal StrictRedisCluster object. The only real error here is that the docs is out of date.

**Comment by Chatheersh** [comment]
Thanks.  Your suggestion worked.
