### ISSUE TITLE
ERROR sending 'config get cluster-require-full-coverage

### ISSUE THREAD

**Issue by 15astro** [Grokzen/redis-py-cluster#303]
Hi @Grokzen,

I am currently seeing many occurences of `ERROR sending 'config get cluster-require-full-coverage` while starting an application which used this redis-py-cluster driver.

When checked here: https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L276 it expects at least one node in the cluster with `cluster-require-full-coverage yes`. With the cluster where `cluster-require-full-coverage` is set to `no` on all nodes, the error keeps re-appearing.

When `cluster-require-full-coverage` was set to `yes` on one of the nodes intentionally, it stops throwing above error.

If the value of skip_full_coverage_check is set to True here: https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L38 it doesn't throw and error.

Please suggest.

Thanks!

**Comment by Grokzen** [comment]
So basically the error is that if you do not have `cluster-require-full-coverage` defined in any of your nodes redis config then the error you mention occurs?

If possible could you please output the exception object and stacktrace that you get from the error object here? https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L273

The try/except block should not fail out with an exception but should just return False from the method call there if the config is not defined or not set at all.

My guess is that you get another unknown error during the connection to all cluster nodes during startup. Possibly that you have nodes defined as startup nodes but that is not reachable for example. The exception object would probably shed some light on what it really is.

**Comment by c0lon** [comment]
I'm getting the same error. Here is the full stack trace

```
Traceback (most recent call last):
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/nodemanager.py", line 270, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/redis/client.py", line 715, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `CONFIG`, with args beginning with: `GET`, `cluster-require-full-coverage`,

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/client.py", line 190, in __init__
    **kwargs
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/connection.py", line 145, in __init__
    self.nodes.initialize()
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/nodemanager.py", line 230, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/nodemanager.py", line 277, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/nodemanager.py", line 277, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/home/hoop/.pyenv/versions/qapi/lib/python3.6/site-packages/rediscluster/nodemanager.py", line 274, in node_require_full_coverage
    raise RedisClusterException("ERROR sending 'config get cluster-require-full-coverage' command to redis server: {0}".format(node))
rediscluster.exceptions.RedisClusterException: ERROR sending 'config get cluster-require-full-coverage' command to redis server: {'host': '*.*.*.*', 'port': 6379, 'name': '*.*.*.*:6379', 'server_type': 'master'}
```

I am using a clustered AWS Elasticache redis instance. I am getting the same error whether I try to connect to the configuration URL or an individual node URL.

**Comment by c0lon** [comment]
Passing `skip_full_coverage_check=True` when initializing the cluster solved the issue.
