### ISSUE TITLE
connot subscribe channels in different server, this bug will always change the host to 127.0.0.1 and execute subscribe command

### ISSUE THREAD

**Issue by weijiayun** [Grokzen/redis-py-cluster#346]
```
Traceback (most recent call last):
  File "/home/jiayunwei/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/jiayunwei/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jiayunwei/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jiayunwei/pycharm-2018.1.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jiayunwei/Project/BTC/ccluoshu/adventure/cluster2.py", line 11, in <module>
    ds.subscribe(["weijiayun"], on_message=on_msg)
  File "/home/jiayunwei/Project/BTC/ccluoshu/shared/base/exchange.py", line 409, in subscribe
    self.add_subscription(channels)
  File "/home/jiayunwei/Project/BTC/ccluoshu/shared/base/exchange.py", line 390, in add_subscription
    self.pubsub.subscribe(new_channels)
  File "/home/jiayunwei/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3026, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/home/jiayunwei/anaconda3/lib/python3.7/site-packages/rediscluster/pubsub.py", line 35, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/home/jiayunwei/anaconda3/lib/python3.7/site-packages/redis/client.py", line 2959, in _execute
    connection.connect()
  File "/home/jiayunwei/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:7002. Connection refused.
```

in nodemanager.py line:186

- if master_node[0] == "":
-      master_node[0] = node['host']
- master_node[1] = int(master_node[1])
change to =>
+ master_node[0] = node['host']
+ master_node[1] = int(master_node[1])

**Comment by Grokzen** [comment]
@weijiayun The documentation on pubsub strongly reccomends that you do not use pubsub in a clustered envrionment https://github.com/Grokzen/redis-py-cluster/blob/master/docs/pubsub.rst

**Comment by weijiayun** [comment]
Thank you so much.
