### ISSUE TITLE
Connection to redis cluster NOT getting extablished 

### ISSUE THREAD

**Issue by satva** [Grokzen/redis-py-cluster#354]
Hi 

**Used S/W Versions :**
          redis-py-cluster: 2.0.0
          redis: 3.0.1
          Python: 3.7.4
          Redis Cluster - (Server Version : 5.0.3) 

Was trying to connect to cluster with below code:

```
##########
startup_node = [{"host": "172.21.97.21", "port": "8605"}]
rc = RedisCluster(startup_nodes=startup_node, decode_responses=True)
#########
```

It was hanging and when issued CTRL-C
```
(venv2) KESRINIV-M-F1GP:Desktop kesriniv$ python redis_test.py 
^CTraceback (most recent call last):
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 169.254.34.45:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "redis_test.py", line 4, in <module>
    rc = RedisCluster(startup_nodes=startup_node, decode_responses=True,readonly_mode=True)
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/client.py", line 214, in __init__
    **kwargs
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/connection.py", line 365, in __init__
    **connection_kwargs)
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/connection.py", line 146, in __init__
    self.nodes.initialize()
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 219, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 266, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 266, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 259, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/client.py", line 845, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/Users/kesriniv/Desktop/abc/venv2/lib/python3.7/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
KeyboardInterrupt
```

**Note** - Using redis-cli , was able to connect to same server.

**Comment by Grokzen** [comment]
@satva Can you post the output from running `cluster info` and `cluster slots` on the cluster itself? I guess that your cluster is tracking the IP `169.254.34.45:6379` on the inside of the cluster but you specify `[{"host": "172.21.97.21", "port": "8605"}]` from the outside in your client. Is it possible that you are running your redis cluster inside a virtualized or containerized envrionment? Maybe in vagrant or docker or similar?

**Comment by satva** [comment]
@Grokzen Yes,  Redis Server (cluster) was running inside docker container (spinned by K8s) & the IP of the eth0 interface inside container was 169.254.34.45. 
172.21.97.21 was HOST IP in which this container was floating.

**Comment by satva** [comment]
Inside Container 
,,,
root@redis-0:/# ifconfig 
eth0      Link encap:Ethernet  HWaddr 7e:ae:51:41:0c:37  
          inet addr:169.254.34.45  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:6456575 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5996592 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2209708788 (2.2 GB)  TX bytes:3379566993 (3.3 GB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:520527 errors:0 dropped:0 overruns:0 frame:0
          TX packets:520527 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:36005089 (36.0 MB)  TX bytes:36005089 (36.0 MB)

root@redis-0:/# netstat -nat
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN   
,,,

**Comment by satva** [comment]
HI @Grokzen  

Given the details , do redis-py-cluster support this environment ?

-Thanks,
Kesav.

**Comment by Grokzen** [comment]
Basically no cluster client will support your cluster setup. Yes there might be some arcane configurations in some clients that can support this type of IP translation. I will try to describe the problem for you and why it is not an problem from this client pov.

When you build and setup your cluster, each redis node must know what IP:port to use to reach any other node in the cluster to be able to provide and serve all data from all cluster slots that exists inside the cluster. When you run `cluster meet` command to build up the cluster, you provide what endpoints that exists inside your cluster and whta IP:PORT they each use. The problem with this is that in case you are inside a virtual machine or most commonly inside a container, you will not have the a IP between the nodes in your cluster as you would require to access the cluster from your clients. And your clients is most commonly outside your container. This is why you see your case with one IP on the inside and one IP on the outside.

My only suggestion that i have is that you have to sort out your IP that redis server itself tracks between your nodes. This might make you require to change your IP setup, or change how/what IP you provide to redis server itself to build the cluster. Then this client will work as normal again and you can connect to your cluster.
