### ISSUE TITLE
Unable to connect to redis cluster (ssl enabled)

### ISSUE THREAD

**Issue by rbharad27** [Grokzen/redis-py-cluster#373]
from rediscluster import RedisCluster

startup_nodes = [{"host": "my_host_name", "port": "6379"}]
rds= RedisCluster(startup_nodes=startup_nodes, ssl=True, password='password', decode_responses=True, skip_full_coverage_check=True)
rds.ping()

Error:
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/redis/connection.py", line 537, in __del__
    self.disconnect()
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/redis/connection.py", line 660, in disconnect
    self._parser.on_disconnect()
AttributeError: 'SSLClusterConnection' object has no attribute '_parser'
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/connection.py", line 318, in get_connection_by_node
    connection = self._available_connections.get(node["name"], []).pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/client.py", line 531, in execute_command
    return self._execute_command(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/client.py", line 556, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/client.py", line 652, in _execute_command_on_nodes
    connection = self.connection_pool.get_connection_by_node(node)
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/connection.py", line 320, in get_connection_by_node
    connection = self.make_connection(node)
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/connection.py", line 227, in make_connection
    connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/rediscluster/connection.py", line 74, in __init__
    super(SSLClusterConnection, self).__init__(**kwargs)
  File "/home/user/.local/share/virtualenvs/fold-Su7CamTZ/lib/python3.6/dist-packages/redis/connection.py", line 819, in __init__
    super(SSLConnection, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'

Any idea about this issue? How can i connect to redis ssl cluster?

**Comment by Grokzen** [comment]
@rbharad27 Try the solution mentioned in this comment on a similar issue https://github.com/Grokzen/redis-py-cluster/issues/369#issuecomment-629215190

**Comment by rbharad27** [comment]
@Grokzen  Adding ssl_cert_reqs='none'/ssl_cert_reqs=False does not help in my case

rds= RedisCluster(startup_nodes=startup_nodes, ssl=True, ssl_cert_reqs=False, password='password', decode_responses=True, skip_full_coverage_check=True)

However, i do not see the earlier error. But does not connect. It just waits for the connection without any error

And also, my redis cluster is AWS manged with Encryption at-rest and Encryption in-transit enabled

**Comment by Grokzen** [comment]
@rbharad27 Okey, are you connecting to the right node? Having the correct node inside your startup nodes list? Secondly one thing you can do, is that you can attempt to connect to any of your nodes through the redis-py library only, becuase if you can do that with some argument into the Redis class, then you should just be able to flip the Redis class into RedisCluster and it should work OOB. Try this and get back to me.

**Comment by rbharad27** [comment]
@Grokzen I tried to connect the redis cluster with redis-py and it worked
import redis
rds = redis.StrictRedis(host='my_host', port=6379, db=0, password='password', ssl=True)
rds.ping()	-- return True

but in redis-py-cluster, it does not respond (just wait, no error or response)

i also tried below with redis cluster using redis-py-cluste and it return the list of nodes in the cluster
rds.connection_pool.nodes.nodes

but ping or other commands does not work

**Comment by Grokzen** [comment]
@rbharad27 What versions of redis-server, redis-py, redis-py-cluster are you using?

**Comment by rbharad27** [comment]
@Grokzen Redis engine: 5.0.6 (AWS managed with authentication and encryption enabled)
I have tried connecting with below 2 versions
- redis-py-cluster 2.0.0 and redis-py 3.0.1
- redis-py-cluster 2.0.99 and redis-py 3.5.2

Also, connection is successful when i have a cluster without  authentication and encryption (no ssl), but not working on a secure cluster for some reason.

**Comment by Grokzen** [comment]
redis-py 3.5.2 or anything above 3.1.0 can only be used with the 2.0.99 (2.1.0-RC1) release that you have. I dont know how to help you further tho then for you to dig through the code some more and try different options from your end. There is a few open issues in the past that i linked in and a few others that talk about the same thing and how they managed to solve it. Try to dig through them a bit more and try to specially take a look and try to debug what options is sent down into the SSLClusterConnection class and further down into redis-py SSLConnection class to see if there is any difference there when you run with redis-py and redis-py-cluster 2.0.99 with the same options in different cases. Maybe there is a option that is not sent down properly from this lib. I dont have AWS going for this use-case so i can't really test it out so much myself right now sorry.

**Comment by jakehilton** [comment]
One thing to note.. the startup nodes you're passing in for AWS should be the config endpoint.
```clustercfg.somename.7yessp.use1.cache.amazonaws.com```
The non encrypted in transit endpoints have a url schema like so:
```somename.7yessp.clustercfg.use1.cache.amazonaws.com ```

Also.. does your test work with the old version of the lib?

**Comment by jakehilton** [comment]
I just tested and can reproduce the same issue. Will see if I can dig in a bit more for details.

**Comment by rbharad27** [comment]
Yup, configuration endpoint is used as host.
For some reason, i am able to connect with older version of redis-py-cluster (2.0.0) and redis-py 3.0.1 but not with 2.0.99 and 3.5.2

Code Snippet:
from rediscluster import RedisCluster
startup_nodes = [{"host": "congiguration_endpoint", "port": "6379"}]
rc = RedisCluster(startup_nodes=startup_nodes, password='password', decode_responses=True, skip_full_coverage_check=True, ssl=True, ssl_cert_reqs=False)
rc.ping()
