### ISSUE TITLE
the code sample in the pipelines document does not work

### ISSUE THREAD

**Issue by fwt11** [Grokzen/redis-py-cluster#384]
this is the error
`Traceback (most recent call last):
  File "test-redis-cluster.py", line 65, in <module>
    p.execute()
  File "/home/fwt/anaconda3/lib/python3.7/site-packages/rediscluster/pipeline.py", line 102, in execute
    return self.send_cluster_commands(stack, raise_on_error)
  File "/home/fwt/anaconda3/lib/python3.7/site-packages/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/home/fwt/anaconda3/lib/python3.7/site-packages/rediscluster/pipeline.py", line 148, in send_cluster_commands
    attempt = sorted(stack, key=lambda x: x.position)
  File "/home/fwt/anaconda3/lib/python3.7/site-packages/rediscluster/pipeline.py", line 148, in <lambda>
    attempt = sorted(stack, key=lambda x: x.position)
AttributeError: 'tuple' object has no attribute 'position'
`

**Comment by Grokzen** [comment]
Good find @fwt11 but i would say that those example is fairly outdated and not really regular examples of how pipelines is supposed to be used or working. That entire pipieline.rst file is not really a example documentation of how to use it but more a discussion on how different solutions can be implemented in pipelines as they rae much more complex to implement in a clustered envrionment.
