### ISSUE TITLE
AttributeError: 'RedisCluster' object has no attribute 'connection'

### ISSUE THREAD

**Issue by levkk** [Grokzen/redis-py-cluster#433]
Happens on interpreter exit:

```
Exception ignored in: <function Redis.__del__ at 0x10a87b280>
Traceback (most recent call last):
  File "/[...]/venv/lib/python3.8/site-packages/redis/client.py", line 885, in __del__
    self.close()
  File "/[...]/venv/lib/python3.8/site-packages/redis/client.py", line 888, in close
    conn = self.connection
AttributeError: 'RedisCluster' object has no attribute 'connection'
```

```
$ pip freeze | grep redis
redis==3.5.3
redis-py-cluster==2.1.0
```

Interpreter: Mac OS X Python 3.8

**Comment by Grokzen** [comment]
@levkk Thank you for this contribution
