### ISSUE TITLE
Command: WAIT is blocked in redis cluster mode

### ISSUE THREAD

**Issue by Vabs3** [Grokzen/redis-py-cluster#486]
Hi

I am working with a Redis cluster. I have setup 3 masters with 1 replica each. I am using redis-py-cluster as a client. While running wait command to synchronise writes to replicas, I am getting following error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "test_redis_new_wait.py", line 235, in method_time_calculator
    method(*args)
  File "test_redis_new_wait.py", line 41, in setnx
    do_wait()
  File "test_redis_new_wait.py", line 31, in do_wait
    CLIENT.wait(WAIT, WAIT_TIMEOUT)
  File "/home/vaibhavgrover/redis_benchmarking/venv/lib64/python3.6/site-packages/redis/client.py", line 1490, in wait
    return self.execute_command('WAIT', num_replicas, timeout)
  File "/home/vaibhavgrover/redis_benchmarking/venv/lib64/python3.6/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
  File "/home/vaibhavgrover/redis_benchmarking/venv/lib64/python3.6/site-packages/rediscluster/client.py", line 579, in _execute_command
    node = self.determine_node(*args, **kwargs)
  File "/home/vaibhavgrover/redis_benchmarking/venv/lib64/python3.6/site-packages/rediscluster/client.py", line 527, in determine_node
    return blocked_command(self, command)
  File "/home/vaibhavgrover/redis_benchmarking/venv/lib64/python3.6/site-packages/rediscluster/utils.py", line 46, in blocked_command
    raise RedisClusterException("Command: {0} is blocked in redis cluster mode".format(command))
rediscluster.exceptions.RedisClusterException: Command: WAIT is blocked in redis cluster mode
````

It is saying wait is blocked in redis cluster mode. But I am able to run wait command in redis-cli -c utility.

Thanks

**Comment by Grokzen** [comment]
Closing due to inactivity. Also if this feature is wanted @Vabs3 you have to now raise it up to the git repo `redis-py` that now have cluster support to see if they are willing to fix or support this feature. It won't be created or built here at least.
